<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $products = [
            // Gaming Laptops
            [
                'category_id' => 6,
                'name' => 'ASUS ROG Strix G15',
                'slug' => 'asus-rog-strix-g15',
                'description' => 'High-performance gaming laptop with AMD Ryzen 9 and RTX 4070',
                'specifications' => json_encode([
                    'processor' => 'AMD Ryzen 9 7945HX',
                    'graphics' => 'NVIDIA GeForce RTX 4070 8GB GDDR6',
                    'ram' => '32GB DDR5 4800MHz',
                    'storage' => '1TB NVMe SSD',
                    'display' => '15.6" FHD 240Hz IPS',
                    'battery' => '90Wh',
                    'weight' => '2.5 kg',
                    'os' => 'Windows 11 Home',
                    'ports' => ['USB-C', 'USB 3.2', 'HDMI 2.1', 'RJ45', '3.5mm Audio'],
                    'warranty' => '2 years',
                ]),
                'price' => 45900000, // 45,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 6,
                'name' => 'MSI Raider GE78 HX',
                'slug' => 'msi-raider-ge78-hx',
                'description' => 'Premium gaming laptop with Intel Core i9 and RTX 4090',
                'specifications' => json_encode([
                    'processor' => 'Intel Core i9-13980HX',
                    'graphics' => 'NVIDIA GeForce RTX 4090 16GB GDDR6',
                    'ram' => '64GB DDR5 5600MHz',
                    'storage' => '2TB NVMe SSD',
                    'display' => '17.3" QHD 240Hz Mini LED',
                    'battery' => '99.9Wh',
                    'weight' => '3.1 kg',
                    'os' => 'Windows 11 Pro',
                    'ports' => ['Thunderbolt 4', 'USB 3.2', 'HDMI 2.1', 'SD Card Reader'],
                    'warranty' => '3 years',
                ]),
                'price' => 89900000, // 89,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 6,
                'name' => 'Lenovo Legion Pro 7i',
                'slug' => 'lenovo-legion-pro-7i',
                'description' => 'Powerful gaming machine with excellent cooling system',
                'specifications' => json_encode([
                    'processor' => 'Intel Core i9-13900HX',
                    'graphics' => 'NVIDIA GeForce RTX 4080 12GB GDDR6',
                    'ram' => '32GB DDR5 5200MHz',
                    'storage' => '1TB NVMe SSD',
                    'display' => '16" WQXGA 240Hz G-SYNC',
                    'battery' => '99.99Wh',
                    'weight' => '2.8 kg',
                    'os' => 'Windows 11 Home',
                    'ports' => ['USB-C', 'USB 3.2', 'HDMI 2.1', 'Ethernet'],
                    'warranty' => '2 years',
                ]),
                'price' => 64500000, // 64,500,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Business Laptops
            [
                'category_id' => 7,
                'name' => 'Dell Latitude 5540',
                'slug' => 'dell-latitude-5540',
                'description' => 'Reliable business laptop with enterprise-grade security',
                'specifications' => json_encode([
                    'processor' => 'Intel Core i7-1355U',
                    'graphics' => 'Intel Iris Xe Graphics',
                    'ram' => '16GB DDR4 3200MHz',
                    'storage' => '512GB NVMe SSD',
                    'display' => '15.6" FHD Anti-Glare',
                    'battery' => '54Wh',
                    'weight' => '1.8 kg',
                    'os' => 'Windows 11 Pro',
                    'ports' => ['USB-C', 'USB 3.2', 'HDMI', 'RJ45', 'SmartCard Reader'],
                    'warranty' => '3 years',
                    'security' => ['TPM 2.0', 'Fingerprint Reader', 'IR Camera'],
                ]),
                'price' => 28900000, // 28,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 7,
                'name' => 'HP EliteBook 840 G10',
                'slug' => 'hp-elitebook-840-g10',
                'description' => 'Premium business laptop with exceptional battery life',
                'specifications' => json_encode([
                    'processor' => 'Intel Core i7-1365U',
                    'graphics' => 'Intel Iris Xe Graphics',
                    'ram' => '32GB DDR5 5200MHz',
                    'storage' => '1TB NVMe SSD',
                    'display' => '14" WUXGA Touch',
                    'battery' => '76Wh',
                    'weight' => '1.4 kg',
                    'os' => 'Windows 11 Pro',
                    'ports' => ['Thunderbolt 4', 'USB-A', 'HDMI 2.1', 'Nano SIM'],
                    'warranty' => '3 years',
                    'security' => ['TPM 2.0', 'Fingerprint', 'IR Camera', 'Privacy Screen'],
                ]),
                'price' => 42900000, // 42,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Ultrabooks
            [
                'category_id' => 8,
                'name' => 'Dell XPS 13 Plus',
                'slug' => 'dell-xps-13-plus',
                'description' => 'Ultra-portable laptop with stunning OLED display',
                'specifications' => json_encode([
                    'processor' => 'Intel Core i7-1360P',
                    'graphics' => 'Intel Iris Xe Graphics',
                    'ram' => '16GB LPDDR5 6000MHz',
                    'storage' => '512GB NVMe SSD',
                    'display' => '13.4" 3.5K OLED Touch',
                    'battery' => '55Wh',
                    'weight' => '1.24 kg',
                    'os' => 'Windows 11 Home',
                    'ports' => ['USB-C Thunderbolt 4 x2'],
                    'warranty' => '1 year',
                ]),
                'price' => 36900000, // 36,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 8,
                'name' => 'MacBook Air M2',
                'slug' => 'macbook-air-m2',
                'description' => 'Lightweight powerhouse with Apple M2 chip',
                'specifications' => json_encode([
                    'processor' => 'Apple M2 8-core CPU',
                    'graphics' => 'Apple M2 10-core GPU',
                    'ram' => '16GB Unified Memory',
                    'storage' => '512GB SSD',
                    'display' => '13.6" Liquid Retina 2560x1664',
                    'battery' => '52.6Wh (up to 18 hours)',
                    'weight' => '1.24 kg',
                    'os' => 'macOS Ventura',
                    'ports' => ['Thunderbolt 4 x2', '3.5mm Audio', 'MagSafe 3'],
                    'warranty' => '1 year',
                ]),
                'price' => 32900000, // 32,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Processors (CPU)
            [
                'category_id' => 9,
                'name' => 'Intel Core i9-14900K',
                'slug' => 'intel-core-i9-14900k',
                'description' => 'Top-tier desktop processor for gaming and content creation',
                'specifications' => json_encode([
                    'cores' => 24,
                    'threads' => 32,
                    'base_clock' => '3.2 GHz',
                    'boost_clock' => '6.0 GHz',
                    'cache' => '36MB Intel Smart Cache',
                    'tdp' => '125W',
                    'socket' => 'LGA1700',
                    'integrated_graphics' => 'Intel UHD Graphics 770',
                    'memory_support' => 'DDR5-5600, DDR4-3200',
                    'pcie' => 'PCIe 5.0',
                ]),
                'price' => 18900000, // 18,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 9,
                'name' => 'AMD Ryzen 9 7950X',
                'slug' => 'amd-ryzen-9-7950x',
                'description' => 'High-performance 16-core processor for enthusiasts',
                'specifications' => json_encode([
                    'cores' => 16,
                    'threads' => 32,
                    'base_clock' => '4.5 GHz',
                    'boost_clock' => '5.7 GHz',
                    'cache' => '80MB (L2+L3)',
                    'tdp' => '170W',
                    'socket' => 'AM5',
                    'integrated_graphics' => 'AMD Radeon Graphics',
                    'memory_support' => 'DDR5-5200',
                    'pcie' => 'PCIe 5.0',
                ]),
                'price' => 19500000, // 19,500,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 10,
                'name' => 'Intel Core i5-13600K',
                'slug' => 'intel-core-i5-13600k',
                'description' => 'Best value gaming processor with excellent performance',
                'specifications' => json_encode([
                    'cores' => 14,
                    'threads' => 20,
                    'base_clock' => '3.5 GHz',
                    'boost_clock' => '5.1 GHz',
                    'cache' => '24MB Intel Smart Cache',
                    'tdp' => '125W',
                    'socket' => 'LGA1700',
                    'integrated_graphics' => 'Intel UHD Graphics 770',
                    'memory_support' => 'DDR5-5600, DDR4-3200',
                    'pcie' => 'PCIe 5.0',
                ]),
                'price' => 8900000, // 8,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Graphics Cards (GPU)
            [
                'category_id' => 11,
                'name' => 'NVIDIA GeForce RTX 4090',
                'slug' => 'nvidia-geforce-rtx-4090',
                'description' => 'Ultimate graphics card for 4K gaming and AI workloads',
                'specifications' => json_encode([
                    'gpu' => 'AD102',
                    'cuda_cores' => 16384,
                    'memory' => '24GB GDDR6X',
                    'memory_bus' => '384-bit',
                    'base_clock' => '2235 MHz',
                    'boost_clock' => '2520 MHz',
                    'tdp' => '450W',
                    'recommended_psu' => '850W',
                    'connectors' => '16-pin PCIe 5.0',
                    'outputs' => ['HDMI 2.1', 'DisplayPort 1.4a x3'],
                    'features' => ['Ray Tracing', 'DLSS 3', 'AV1 Encode/Decode'],
                ]),
                'price' => 52900000, // 52,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 12,
                'name' => 'AMD Radeon RX 7900 XTX',
                'slug' => 'amd-radeon-rx-7900-xtx',
                'description' => 'High-end AMD graphics card with excellent rasterization',
                'specifications' => json_encode([
                    'gpu' => 'Navi 31',
                    'stream_processors' => 6144,
                    'memory' => '24GB GDDR6',
                    'memory_bus' => '384-bit',
                    'game_clock' => '2300 MHz',
                    'boost_clock' => '2500 MHz',
                    'tdp' => '355W',
                    'recommended_psu' => '800W',
                    'connectors' => '8-pin x2',
                    'outputs' => ['HDMI 2.1', 'DisplayPort 2.1 x2'],
                    'features' => ['Ray Tracing', 'FSR 3', 'AV1 Encode/Decode'],
                ]),
                'price' => 28900000, // 28,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 10,
                'name' => 'NVIDIA GeForce RTX 4070 Ti',
                'slug' => 'nvidia-geforce-rtx-4070-ti',
                'description' => 'Perfect balance of performance and price for 1440p gaming',
                'specifications' => json_encode([
                    'gpu' => 'AD104',
                    'cuda_cores' => 7680,
                    'memory' => '12GB GDDR6X',
                    'memory_bus' => '192-bit',
                    'base_clock' => '2310 MHz',
                    'boost_clock' => '2610 MHz',
                    'tdp' => '285W',
                    'recommended_psu' => '700W',
                    'connectors' => '16-pin PCIe 5.0',
                    'outputs' => ['HDMI 2.1', 'DisplayPort 1.4a x3'],
                    'features' => ['Ray Tracing', 'DLSS 3', 'Reflex'],
                ]),
                'price' => 22900000, // 22,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Motherboards
            [
                'category_id' => 11,
                'name' => 'ASUS ROG Maximus Z790 Hero',
                'slug' => 'asus-rog-maximus-z790-hero',
                'description' => 'Premium Z790 motherboard for Intel 13th/14th gen CPUs',
                'specifications' => json_encode([
                    'socket' => 'LGA1700',
                    'chipset' => 'Intel Z790',
                    'form_factor' => 'ATX',
                    'memory' => 'DDR5, 4 x DIMM, Max 192GB',
                    'memory_speed' => 'Up to 7800MHz (OC)',
                    'pcie_slots' => ['PCIe 5.0 x16', 'PCIe 4.0 x16', 'PCIe 3.0 x1 x2'],
                    'storage' => ['M.2 PCIe 5.0 x4', 'M.2 PCIe 4.0 x4 x4', 'SATA 6Gb/s x8'],
                    'usb' => ['USB 3.2 Gen 2x2 x2', 'USB 3.2 Gen 2 x6', 'USB 2.0 x4'],
                    'networking' => ['2.5Gb Ethernet', 'WiFi 6E', 'Bluetooth 5.3'],
                    'audio' => 'SupremeFX 7.1 Surround Sound',
                ]),
                'price' => 18900000, // 18,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 11,
                'name' => 'MSI MAG B650 TOMAHAWK WiFi',
                'slug' => 'msi-mag-b650-tomahawk-wifi',
                'description' => 'Feature-rich B650 motherboard for AMD Ryzen 7000 series',
                'specifications' => json_encode([
                    'socket' => 'AM5',
                    'chipset' => 'AMD B650',
                    'form_factor' => 'ATX',
                    'memory' => 'DDR5, 4 x DIMM, Max 128GB',
                    'memory_speed' => 'Up to 6400MHz (OC)',
                    'pcie_slots' => ['PCIe 4.0 x16', 'PCIe 3.0 x16', 'PCIe 3.0 x1'],
                    'storage' => ['M.2 PCIe 4.0 x4 x3', 'SATA 6Gb/s x6'],
                    'usb' => ['USB 3.2 Gen 2x2', 'USB 3.2 Gen 2 x4', 'USB 2.0 x6'],
                    'networking' => ['2.5Gb Ethernet', 'WiFi 6E', 'Bluetooth 5.3'],
                    'audio' => 'Realtek ALC4080',
                ]),
                'price' => 7900000, // 7,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // RAM
            [
                'category_id' => 12,
                'name' => 'Corsair Dominator Platinum RGB DDR5',
                'slug' => 'corsair-dominator-platinum-rgb-ddr5',
                'description' => 'Premium DDR5 RAM with stunning RGB lighting',
                'specifications' => json_encode([
                    'type' => 'DDR5',
                    'capacity' => '32GB (2x16GB)',
                    'speed' => '6000MHz',
                    'cas_latency' => 'CL36',
                    'voltage' => '1.35V',
                    'rgb' => 'Yes - Corsair iCUE Compatible',
                    'heat_spreader' => 'Aluminum',
                    'warranty' => 'Lifetime',
                    'xmp' => 'Intel XMP 3.0',
                    'expo' => 'AMD EXPO',
                ]),
                'price' => 5900000, // 5,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 12,
                'name' => 'G.SKILL Trident Z5 RGB DDR5',
                'slug' => 'gskill-trident-z5-rgb-ddr5',
                'description' => 'High-performance DDR5 memory for enthusiasts',
                'specifications' => json_encode([
                    'type' => 'DDR5',
                    'capacity' => '64GB (2x32GB)',
                    'speed' => '6400MHz',
                    'cas_latency' => 'CL32',
                    'voltage' => '1.4V',
                    'rgb' => 'Yes - RGB Fusion 2.0',
                    'heat_spreader' => 'Aluminum',
                    'warranty' => 'Lifetime',
                    'xmp' => 'Intel XMP 3.0',
                    'expo' => 'AMD EXPO',
                ]),
                'price' => 11900000, // 11,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // SSD Storage
            [
                'category_id' => 21,
                'name' => 'Samsung 990 Pro',
                'slug' => 'samsung-990-pro',
                'description' => 'Flagship PCIe 4.0 NVMe SSD with exceptional speed',
                'specifications' => json_encode([
                    'capacity' => '2TB',
                    'interface' => 'PCIe 4.0 x4, NVMe 2.0',
                    'form_factor' => 'M.2 2280',
                    'sequential_read' => '7450 MB/s',
                    'sequential_write' => '6900 MB/s',
                    'random_read' => '1,400K IOPS',
                    'random_write' => '1,550K IOPS',
                    'controller' => 'Samsung Proprietary',
                    'nand' => 'Samsung V-NAND 3-bit MLC',
                    'dram' => '2GB LPDDR4',
                    'warranty' => '5 years',
                    'tbw' => '1200 TB',
                ]),
                'price' => 7900000, // 7,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 21,
                'name' => 'WD Black SN850X',
                'slug' => 'wd-black-sn850x',
                'description' => 'High-performance gaming SSD with heatsink',
                'specifications' => json_encode([
                    'capacity' => '1TB',
                    'interface' => 'PCIe 4.0 x4, NVMe 1.4',
                    'form_factor' => 'M.2 2280',
                    'sequential_read' => '7300 MB/s',
                    'sequential_write' => '6300 MB/s',
                    'random_read' => '1,200K IOPS',
                    'random_write' => '1,100K IOPS',
                    'controller' => 'Western Digital',
                    'nand' => 'BiCS5 112L 3D TLC',
                    'dram' => '1GB DDR4',
                    'heatsink' => 'Included',
                    'warranty' => '5 years',
                    'tbw' => '600 TB',
                ]),
                'price' => 3900000, // 3,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Keyboards
            [
                'category_id' => 16,
                'name' => 'Corsair K70 RGB PRO',
                'slug' => 'corsair-k70-rgb-pro',
                'description' => 'Premium mechanical gaming keyboard with Cherry MX switches',
                'specifications' => json_encode([
                    'switch_type' => 'Cherry MX Red',
                    'backlight' => 'Per-key RGB',
                    'connection' => 'USB Type-C (Detachable)',
                    'layout' => 'Full-size (104 keys)',
                    'keycaps' => 'Double-shot PBT',
                    'polling_rate' => '1000Hz',
                    'frame' => 'Aluminum',
                    'wrist_rest' => 'Included',
                    'media_keys' => 'Dedicated',
                    'software' => 'Corsair iCUE',
                    'warranty' => '2 years',
                ]),
                'price' => 3900000, // 3,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 16,
                'name' => 'Logitech G915 TKL',
                'slug' => 'logitech-g915-tkl',
                'description' => 'Wireless low-profile mechanical gaming keyboard',
                'specifications' => json_encode([
                    'switch_type' => 'GL Tactile Low-profile',
                    'backlight' => 'Per-key RGB LIGHTSYNC',
                    'connection' => 'Wireless (LIGHTSPEED) / Bluetooth / USB',
                    'layout' => 'Tenkeyless (87 keys)',
                    'keycaps' => 'ABS',
                    'polling_rate' => '1000Hz',
                    'battery' => 'Up to 40 hours',
                    'frame' => 'Aluminum',
                    'media_keys' => 'Dedicated',
                    'software' => 'Logitech G HUB',
                    'warranty' => '2 years',
                ]),
                'price' => 5900000, // 5,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mice
            [
                'category_id' => 17,
                'name' => 'Logitech G Pro X Superlight',
                'slug' => 'logitech-g-pro-x-superlight',
                'description' => 'Ultra-lightweight wireless gaming mouse for esports',
                'specifications' => json_encode([
                    'sensor' => 'HERO 25K',
                    'dpi' => '100-25,600',
                    'ips' => '400+',
                    'connection' => 'Wireless LIGHTSPEED',
                    'battery' => 'Up to 70 hours',
                    'weight' => '63g',
                    'buttons' => 5,
                    'rgb' => 'No',
                    'feet' => 'PTFE',
                    'warranty' => '2 years',
                ]),
                'price' => 3500000, // 3,500,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 17,
                'name' => 'Razer DeathAdder V3 Pro',
                'slug' => 'razer-deathadder-v3-pro',
                'description' => 'Wireless ergonomic gaming mouse with Focus Pro sensor',
                'specifications' => json_encode([
                    'sensor' => 'Focus Pro 30K',
                    'dpi' => '100-30,000',
                    'ips' => '750',
                    'connection' => 'Wireless HyperSpeed / Bluetooth / USB-C',
                    'battery' => 'Up to 90 hours',
                    'weight' => '63g',
                    'buttons' => 8,
                    'rgb' => 'Razer Chroma RGB',
                    'switches' => 'Razer Optical Gen-3',
                    'warranty' => '2 years',
                ]),
                'price' => 3900000, // 3,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Monitors
            [
                'category_id' => 18,
                'name' => 'LG 27GR95QE-B UltraGear',
                'slug' => 'lg-27gr95qe-b-ultragear',
                'description' => '27" OLED gaming monitor with 240Hz refresh rate',
                'specifications' => json_encode([
                    'size' => '27 inches',
                    'panel' => 'OLED',
                    'resolution' => '2560x1440 (QHD)',
                    'refresh_rate' => '240Hz',
                    'response_time' => '0.03ms GtG',
                    'hdr' => 'HDR10, DisplayHDR True Black 400',
                    'adaptive_sync' => 'G-SYNC Compatible, FreeSync Premium',
                    'inputs' => ['HDMI 2.1 x2', 'DisplayPort 1.4'],
                    'stand' => 'Height/Tilt/Pivot adjustable',
                    'speakers' => 'No',
                    'warranty' => '3 years',
                ]),
                'price' => 26900000, // 26,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 18,
                'name' => 'ASUS ROG Swift PG27AQDM',
                'slug' => 'asus-rog-swift-pg27aqdm',
                'description' => '27" QD-OLED gaming monitor with exceptional colors',
                'specifications' => json_encode([
                    'size' => '27 inches',
                    'panel' => 'QD-OLED',
                    'resolution' => '2560x1440 (QHD)',
                    'refresh_rate' => '240Hz',
                    'response_time' => '0.03ms GtG',
                    'hdr' => 'HDR10, DisplayHDR True Black 400',
                    'adaptive_sync' => 'G-SYNC Compatible',
                    'color_gamut' => 'DCI-P3 99%',
                    'inputs' => ['HDMI 2.0 x2', 'DisplayPort 1.4', 'USB Hub'],
                    'stand' => 'Height/Tilt/Swivel/Pivot',
                    'warranty' => '3 years',
                ]),
                'price' => 29900000, // 29,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Power Supply
            [
                'category_id' => 13,
                'name' => 'Corsair RM1000x',
                'slug' => 'corsair-rm1000x',
                'description' => '1000W 80 PLUS Gold fully modular power supply',
                'specifications' => json_encode([
                    'wattage' => '1000W',
                    'efficiency' => '80 PLUS Gold',
                    'modular' => 'Fully Modular',
                    'fan' => '135mm Fluid Dynamic',
                    'pfc' => 'Active PFC',
                    'rails' => 'Single +12V Rail (83A)',
                    'connectors' => [
                        'ATX 24-pin' => 1,
                        'EPS 8-pin' => 2,
                        'PCIe 8-pin' => 8,
                        'SATA' => 12,
                        'Molex' => 6,
                    ],
                    'warranty' => '10 years',
                ]),
                'price' => 5900000, // 5,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // PC Case
            [
                'category_id' => 14,
                'name' => 'Lian Li O11 Dynamic EVO',
                'slug' => 'lian-li-o11-dynamic-evo',
                'description' => 'Premium ATX case with excellent airflow and build quality',
                'specifications' => json_encode([
                    'type' => 'Mid-Tower',
                    'form_factor' => 'ATX, Micro-ATX, Mini-ITX',
                    'material' => 'Aluminum & Tempered Glass',
                    'motherboard' => 'ATX, EATX, Micro-ATX, Mini-ITX',
                    'gpu_clearance' => '420mm',
                    'cpu_cooler_height' => '167mm',
                    'radiator_support' => ['Top: 360mm', 'Side: 360mm', 'Bottom: 360mm'],
                    'drive_bays' => ['2.5" x4', '3.5" x2'],
                    'fans_included' => 'None',
                    'usb' => ['USB 3.2 Gen 2 Type-C', 'USB 3.0 x2'],
                    'dimensions' => '476 x 272 x 466mm',
                ]),
                'price' => 4900000, // 4,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Cooling
            [
                'category_id' => 15,
                'name' => 'NZXT Kraken X73 RGB',
                'slug' => 'nzxt-kraken-x73-rgb',
                'description' => '360mm AIO liquid cooler with stunning RGB',
                'specifications' => json_encode([
                    'type' => 'AIO Liquid Cooler',
                    'radiator_size' => '360mm',
                    'fan_size' => '120mm x3',
                    'fan_speed' => '500-2000 RPM',
                    'noise_level' => '21-36 dBA',
                    'rgb' => 'Yes - Addressable RGB',
                    'pump_speed' => '800-2800 RPM',
                    'socket_support' => ['Intel LGA 1700/1200/115x', 'AMD AM5/AM4'],
                    'warranty' => '6 years',
                ]),
                'price' => 6900000, // 6,900,000 VND
                'currency' => 'VND',
                'image' => null,
                'status' => true,
                'parent_id' => null,
                'language' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('products')->insert($products);
    }
}
